# Generated by Django 5.1.5 on 2025-01-26 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_testmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TestModel',
        ),
    ]
